// <auto-generated />
using System;
using DesafioBenjamin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioBenjamin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923195916_AddTentativaQuestoes")]
    partial class AddTentativaQuestoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DesafioBenjamin.Models.Alternativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Correta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explicacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capitulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Questionarios");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Acertou")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlternativaSelecionadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RespondidaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaSelecionadaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("TentativaId");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Tentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("TEXT");

                    b.Property<double>("PercentualAcertos")
                        .HasColumnType("REAL");

                    b.Property<int>("QuestionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalErros")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuestoes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Tentativas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.TentativaQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TentativaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("TentativaId");

                    b.ToTable("TentativaQuestoes");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Alternativa", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questao", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Questionario", "Questionario")
                        .WithMany("Questoes")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questionario", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Disciplina", "Disciplina")
                        .WithMany("Questionarios")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Resposta", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Alternativa", "AlternativaSelecionada")
                        .WithMany()
                        .HasForeignKey("AlternativaSelecionadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioBenjamin.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioBenjamin.Models.Tentativa", "Tentativa")
                        .WithMany("Respostas")
                        .HasForeignKey("TentativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativaSelecionada");

                    b.Navigation("Questao");

                    b.Navigation("Tentativa");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Tentativa", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Aluno", "Aluno")
                        .WithMany("Tentativas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioBenjamin.Models.Questionario", "Questionario")
                        .WithMany("Tentativas")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.TentativaQuestao", b =>
                {
                    b.HasOne("DesafioBenjamin.Models.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioBenjamin.Models.Tentativa", "Tentativa")
                        .WithMany("Questoes")
                        .HasForeignKey("TentativaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Tentativa");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Aluno", b =>
                {
                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Disciplina", b =>
                {
                    b.Navigation("Questionarios");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questao", b =>
                {
                    b.Navigation("Alternativas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Questionario", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("DesafioBenjamin.Models.Tentativa", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
